import CoreGraphics
import CoreImage
import CoreML
import Foundation

/// Splits a photo into garment masks. The model only exists on iOS, so the
/// protocol is what the rest of the app depends on — same shape as
/// `PhotoLibraryService` and `PhotoLibrarySaveService`.
public protocol GarmentSegmentationService: Sendable {
    func segment(_ image: CGImage) throws -> GarmentSegmentation?
}

// MARK: - Cut-outs (pure, cross-platform, unit-testable)

public extension GarmentSegmentationService {
    /// One pass over the class map produces every category's cut-out, instead
    /// of scanning once per category. Each one comes out repaired (§7) and on
    /// the shared 1024² canvas.
    func cutouts(from segmentation: GarmentSegmentation) -> [GarmentCategory: GarmentCutout] {
        let masks = GarmentMask.build(from: segmentation.classMap)
        guard !masks.isEmpty else { return [:] }

        let photo = CIImage(cgImage: segmentation.image)
        let context = CIContext()
        var results: [GarmentCategory: GarmentCutout] = [:]

        for (category, mask) in masks {
            guard let repaired = GarmentMask.repair(mask),
                  let cutout = GarmentMask.cutout(photo: photo, repaired: repaired, context: context),
                  let normalized = GarmentNormalization.normalize(cutout)
            else { continue }
            results[category] = GarmentCutout(image: normalized, maskQuality: repaired.quality)
        }
        return results
    }
}

// MARK: - Implementations

#if os(iOS)
    /// The FASHN SegFormer model. Its Swift class is generated by Xcode's
    /// `CoreMLModelCodegen`, which SwiftPM does not run — hence the platform gate.
    public struct FASHNGarmentSegmentationService: GarmentSegmentationService {
        private static let inputSize = (width: 384, height: 576)

        /// Loaded once for the whole process: the weights are ~128 MB, and the
        /// previous code re-loaded them for every single photo.
        ///
        /// nonisolated(unsafe): the generated wrapper is not `Sendable`, but it
        /// is immutable once loaded and `MLModel` predictions are thread-safe.
        private nonisolated(unsafe) static let model: FASHNSegFormer? = {
            let configuration = MLModelConfiguration()
            configuration.computeUnits = .cpuAndGPU
            do {
                return try FASHNSegFormer(configuration: configuration)
            } catch {
                Log.report(error)
                return nil
            }
        }()

        public init() {}

        public func segment(_ image: CGImage) throws -> GarmentSegmentation? {
            guard let model = Self.model else { throw AppError.unexpected }
            guard let input = GarmentMask.pixelBuffer(
                from: image,
                width: Self.inputSize.width,
                height: Self.inputSize.height
            ) else { return nil }

            let prediction = try model.prediction(image: input)
            let classMap = GarmentMask.argmax(logits: prediction.logits)
            guard !classMap.isEmpty else { return nil }
            return GarmentSegmentation(classMap: classMap, image: image)
        }
    }
#else
    /// macOS host builds and unit tests have no compiled model.
    public struct NoopGarmentSegmentationService: GarmentSegmentationService {
        public init() {}
        public func segment(_: CGImage) throws -> GarmentSegmentation? {
            nil
        }
    }
#endif
