[package]
name = "wardrobe-storage"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
aws-sdk-s3.workspace = true
aws-smithy-http-client.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
reqwest.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
uuid.workspace = true

[lints]
workspace = true
